version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Build the Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t your_image_name:latest .

      # Authenticate with Docker Hub (or your preferred registry)
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Push the Docker image to Docker Hub
      - run:
          name: Push Docker Image
          command: |
            docker tag your_image_name:latest $DOCKER_USERNAME/your_image_name:latest
            docker push $DOCKER_USERNAME/your_image_name:latest
