version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - setup_remote_docker

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Build the Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t projet_node .

      # Authenticate with Docker Hub (or your preferred registry)
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Push the Docker image to Docker Hub
      - run:
          name: Push Docker Image
          command: |
            docker tag projet_node:latest $DOCKER_USERNAME/projet_node:latest
            docker push $DOCKER_USERNAME/projet_node:latest

      # Run tests
      - run:
          name: Test Docker Container
          command: |
            docker run -d -p 8080:8080 your_image_name:latest
            sleep 10 # Wait for the container to start
            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/your-route) # Send a request to your route
            if [ $response -eq 200 ]; then
              echo "Test passed: Server responded successfully"
              exit 0
            else
              echo "Test failed: Server did not respond as expected"
              exit 1
            fi
